### PR TITLE
Use Ohsome instead of OSM API

### LINKED ISSUE #1: Too many entities
If more than 50.000 entities are requested the API fails with an  HTTP status code 400 (Bad Request).
A insightful message should be displayed instead of the generic one.

### LINKED ISSUE #137: Use Ohsome API
Supersedes #2.

This is needed to improve performance and further extend is-osm-uptodate capabilities.

### PR DESCRIPTION
**Pull request by frafra**
Fix #1 and #137.

Benefits :+1::
- Better performances: is much faster to do a simple metadata request to Ohsome than thousands of multiple requests to the OSM API
- Can load larger area: there is no limit on the amount of nodes that can be retrieved with Ohsome (or at least it looks like it is very high)
- Lower memory usage: data is received, processed and sent at the same time (as a stream), instead of having multiple steps which store the whole partial result in memory before starting the following
- Stop hitting OSM API hard: I never received any complaint with respect to is-osm-uptodate usage of OSM API and I tried to respect the API policy as closely as possible, but in general OSM API should not be used for reading data, if not for editing it later; is-osm-uptodate is then in a gray area at the moment
- Data transfer starts as soon as the data is processed, which is beneficial for slow connections

Defects :-1::
- No information about unique contributors (https://github.com/GIScience/ohsome-api/issues/182)
- Some nodes without tags could be rendered (https://github.com/GIScience/ohsome-api/issues/210)
- No ways (Ohsome is much slower when requesting ways)
- No tags, but they can be retrieved by clicking on "details"; this defect could be fixed by requesting the tags just when opening the popup

Additional notes:
- `average_update_days` is now computed on the backend instead of the frontend
- No cache, but the performances are so much better that it is not needed at the moment
- Groundwork to implement #5.

Demo: https://is-osm-uptodate.fly.dev

### CODE REVIEW

**Comment by frafra** [comment]
There are some issues with CircleCI, but local tests work as expected.

**Comment by frafra** [comment]
Results seem consistent with the original OSM API based version.

**Comment by frafra** [comment]
Bounding box: `9.1857564449 45.4615305496 9.1972362995 45.4669934906`

Performances for revision 4651f7559055301c816738aaf3ae7b34e6f10b4d (ohsome branch): 3''
Performances for revision 835b9037a32cac9da2cca48d5f0b1102f9cd1946 (master branch): 40''

```
(venv) [frafra@e32 is-osm-uptodate]$ git rev-parse HEAD; time ./is-osm-uptodate.py 9.1857564449 45.4615305496 9.1972362995 45.4669934906 > /dev/null
4651f7559055301c816738aaf3ae7b34e6f10b4d

real	0m2.936s
user	0m0.280s
sys	0m0.036s
(venv) [frafra@e32 is-osm-uptodate]$ git checkout master
Switched to branch 'master'
Your branch is up to date with 'origin/master'.
(venv) [frafra@e32 is-osm-uptodate]$ git rev-parse HEAD; time ./is-osm-uptodate.py 9.1857564449 45.4615305496 9.1972362995 45.4669934906 > /dev/null
835b9037a32cac9da2cca48d5f0b1102f9cd1946

real	0m39.646s
user	0m4.914s
sys	0m0.240s
```

**Comment by frafra** [comment]
Bounding box: 9.188295196 45.4635324507 9.1926242813 45.4649771956

Performances for revision 4651f75 (ohsome branch): 3''
Performances for revision 835b903 (master branch): 6''

```
(venv) [frafra@e32 is-osm-uptodate]$ git rev-parse HEAD; time ./is-osm-uptodate.py 9.188295196 45.4635324507 9.1926242813 45.4649771956 > /dev/null
835b9037a32cac9da2cca48d5f0b1102f9cd1946

real	0m5.869s
user	0m0.957s
sys	0m0.092s
(venv) [frafra@e32 is-osm-uptodate]$ git checkout ohsome
Switched to branch 'ohsome'
Your branch is up to date with 'origin/ohsome'.
(venv) [frafra@e32 is-osm-uptodate]$ git rev-parse HEAD; time ./is-osm-uptodate.py 9.188295196 45.4635324507 9.1926242813 45.4649771956 > /dev/null
4651f7559055301c816738aaf3ae7b34e6f10b4d

real	0m2.615s
user	0m0.205s
sys	0m0.024s
```

The time for fetching data from the OSM API seems to be linearly dependent on the number of elements, but Ohsome does not take more time. Computation is also more efficient and simpler too.

**Comment by frafra** [comment]
More performance testing with more than > 50.000 currently available nodes:

```
(venv) [frafra@e32 is-osm-uptodate]$ time ./is-osm-uptodate.py 9.139244 45.442408 9.221985 45.498747 > milano-circonvallazione-esterna.json

real	0m8.853s
user	0m2.339s
sys	0m0.454s
(venv) [frafra@e32 is-osm-uptodate]$ jq '.features | length' < milano-circonvallazione-esterna.json 
66155
```

**Comment by frafra** [comment]
I found an issue: nodes that had tags in the past, but they do not have them anymore, are represented.

**Comment by frafra** [comment]
Ohsome API can return big JSON files (~100 MB uncompressed): at that size, much more RAM is needed to allocate space for such response, which has to be passed to SQLite, parsed, and the final result has to be converted into JSON again and sent to the webapp. That means that for large areas (~70.000 nodes), an additional 550 MB of available RAM are needed, for each request. I discovered such problem because my small VM on fly.io was failing to process the data.

As versions of the same node are located in contiguous areas of the original JSON file, is it possible to process the JSON file while streaming. After some changes and profiling, the memory usage for each request is negligible, and the performance penalty is low (15 % slower than the SQLite version):

```
time curl 'http://localhost:8000/api/getData?minx=9.139244&miny=45.442408&maxx=9.221985&maxy=45.498747' >/dev/null
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 15.3M    0 15.3M    0     0  1550k      0 --:--:--  0:00:10 --:--:-- 2956k

real	0m10.148s
user	0m0.409s
sys	0m1.207s
```

I then decided to merge this additional change in this PR.

**Comment by frafra** [comment]
> I found an issue: nodes that had tags in the past, but they do not have them anymore, are shown.

I opened an issue: https://github.com/GIScience/ohsome-api/issues/210

**Review by MarcoMinghini — APPROVED** [review]
This PR provides a number of improvements to the previous system, from the performance (analysing large areas was one of the goals) to the use of the OSM API that was not recommended. The disadvantages are also important, because the lack of information about contributors prevents the use of some intrinsic quality measures (average number of different contributors who edited the same object) and ways cannot be analysed anymore.

Overall, I think the advantages outweigh the disadvantages so I am in favour to change the whole architecture by moving to Ohsome.

However, given that the main change (from the user perspective) is the chance to analyse larger areas - I tried and it works pretty well at a city-level area, I would strongly suggest to display the value of (at least) all the average quality metrics (average date of first edit, average date of last edit, average number of revisions, average update frequency) calculated for the current bounding box, everytime the user fetches data. This should be then further refined, e.g. to also provide the minimum, maximum and standard deviation of each metric, and ad hoc plots can be also added.

**Comment by frafra** [comment]
@MarcoMinghini thanks for your review :)

Statistics on contributors should be added back in the following weeks/months, as the developers working on Ohsome are planning to implement them in a GDPR-compliant way.

Aggregated statistics for the current bounding box seem to be a good idea indeed. I will open an issue for that then :)

**Pull request merged**
